pizza_app:
    resource: "@PizzaAppBundle/Resources/config/routing.yml"
    prefix:   /


insta_cook:
    resource: "@PizzaCookBundle/Resources/config/routing.yml"
    prefix:   /
    options:
        expose: true

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"