<?php

namespace Pizza\CookBundle\Repository;

/**
 * PizzaIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PizzaIngredientRepository extends \Doctrine\ORM\EntityRepository
{
}
